version: '3.9'

services:
  php:
    container_name: php2
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - "./html:/var/www/html"
    networks:
      - app_network
    depends_on:
      - mysql
   
  nginx:
    image: nginx:latest
    container_name: nginx_server1
    ports:
      - "8082:80"
    volumes:
      - "C:/Users/MSII/Documents/DockerProject/html:/var/www/html"
    configs:
      - source: nginx_config
      - target: ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - php

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: nami123  # Menggunakan variabel dari .env
      MYSQL_DATABASE: dabeee
      MYSQL_USER: nadineumi
      MYSQL_PASSWORD: nami1234
    volumes:
      - mysql_volume2:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app_network
  
  phpmyadmin:
    container_name: phpmyadmin_2
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD= nami123
    depends_on:
      - mysql
    networks:
      - app_network

configs:
  nginx_config:
    file: ./nginx/default.conf

volumes:
  mysql_volume2:

networks:
  app_network:
    driver: bridge
